INSERT INTO games (title, genre, publisher, systemPreference, rating, createdAt, updatedAt) VALUES ("Grand Theft Auto V", "Action", "Rockstar", "Xbox ONE", "9", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO games (title, genre, publisher, systemPreference, rating, createdAt, updatedAt) VALUES ("Halo 3", "Shooter", "Microsoft", "Xbox 360", "9", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO games (title, genre, publisher, systemPreference, rating, createdAt, updatedAt) VALUES ("Horizon Zero Dawn", "Action", "Sony", "PC", "9", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO games (title, genre, publisher, systemPreference, rating, createdAt, updatedAt) VALUES ("Persona 5", "RPG", "Atlus", "Playstation 4", "9", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO games (title, genre, publisher, systemPreference, rating, createdAt, updatedAt) VALUES ("Pokemon Go", "RPG", "Niantic", "Android", "9", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO games (title, genre, publisher, systemPreference, rating, createdAt, updatedAt) VALUES ("Star Wars: Jedi Fallen Order", "Adventure", "EA", "Xbox One", "9", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO games (title, genre, publisher, systemPreference, rating, createdAt, updatedAt) VALUES ("The Legend of Zelda: Breath of the Wild", "Adventure", "Nintendo", "Nintendo Switch", "9", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO games (title, genre, publisher, systemPreference, rating, createdAt, updatedAt) VALUES ("The Witcher 3: Wild Hunt", "Action", "CDProjekt red", "Playstation 4", "9", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO games (title, genre, publisher, systemPreference, rating, createdAt, updatedAt) VALUES ("Uncharted 4: A Thief's End", "Adventure", "Sony", "Playstation 4", "9", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
